"""Add core operational models

Revision ID: 90dc254dc794
Revises: 7be21b3c9aa1
Create Date: 2026-09-04 09:31:25.104361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90dc254dc794'
down_revision: Union[str, None] = '7be21b3c9aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_code'), 'facilities', ['code'], unique=True)
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=False)
    op.create_index(op.f('ix_facilities_name'), 'facilities', ['name'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('AVAILABLE', 'RESERVED', 'IN_USE', 'CLEANING', 'MAINTENANCE', 'RETIRED', name='equipmentstate'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_name'), 'equipment', ['name'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVATING', 'ACTIVE', 'CONTAINMENT', 'DEESCALATING', 'RECOVERY', 'CLOSED', name='incidentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_table('transport_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('origin_location', sa.String(), nullable=False),
    sa.Column('destination_location', sa.String(), nullable=False),
    sa.Column('transport_type', sa.Enum('WHEELCHAIR', 'STRETCHER', 'WALKING_ASSIST', 'BED_TRANSPORT', 'ESCORT', 'OTHER_OPERATIONAL', name='transporttype'), nullable=False),
    sa.Column('priority', sa.Enum('ROUTINE', 'PRIORITY', 'URGENT', 'STAT', name='transportpriority'), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_porter_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'QUEUED', 'ASSIGNED', 'ACCEPTED', 'IN_PROGRESS', 'ARRIVED', 'COMPLETED', 'CANCELLED', name='transportstatus'), nullable=True),
    sa.Column('required_equipment', sa.String(), nullable=True),
    sa.Column('special_requirements', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_porter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_requests_id'), 'transport_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transport_requests_id'), table_name='transport_requests')
    op.drop_table('transport_requests')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_equipment_name'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_facilities_name'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_code'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
