@echo off
echo Starting SmartBed Flow...
start cmd /c "cd backend && call venv\Scripts\activate && uvicorn app.main:app --reload --port 8000"
start cmd /c "cd frontend && npm run dev"
echo Application starting...
